name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "part11fso" 
          heroku_email: "atukadagio123@gmail.com"
          healthcheck: "https://part11fso.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
